baseURL = ""
languageCode = "en-us"
title = "BIT.MY.ID"
assetsDir = "assets"
publishDir = "public"
DefaultContentLanguage = "id"
disableKinds = ["taxonomyTerm"]

[languages]
    [languages.id]
        nameLong = "BIT.MY.ID"
        nameShort = "BITMYID"
        languageName = "Bahasa Indonesia"
        title = "Beranda"
        weight = 1

    [languages.en]
        nameLong = "BIT.MY.ID"
        nameShort = "BITMYID"
        languageName = "English"
        title = "Home"
        weight = 2